window.siteContent = {
  meta: {
    title: "Alessandro Esposito | IT Architecture Consultant",
    description:
      "Portfolio professionale di Alessandro Esposito, IT Architecture Consultant: competenze, case study, percorso, certificazioni e contatti in un unico hub digitale.",
  },
  person: {
    name: "Alessandro Esposito",
    initials: "AE",
    role: "IT Architecture Consultant",
    email: "espositoalessandro1997@gmail.com",
    linkedin: "https://www.linkedin.com/in/alessandro-esposito-0880751a6/",
    cvPath: "documents/cv/Alessandro_Esposito_CV_ITA.pdf",
  },
  navigation: [
    { label: "Profilo", target: "#profilo" },
    { label: "Competenze e Case Study", target: "#competenze" },
    { label: "Percorso", target: "#percorso" },
    { label: "Certificati", target: "#certificati" },
    { label: "Contatti", target: "#contatti" },
  ],
  hero: {
    eyebrow: "IT Architecture Consultant",
    title: "Alessandro Esposito",
    copy:
      "Hub professionale per esplorare competenze, metodo di lavoro, percorso e case study: una fonte unica pensata per sostituire CV tradizionale e profilo LinkedIn.",
    primaryAction: { label: "Vedi competenze e case study", target: "#competenze" },
    secondaryAction: { label: "Apri CV", target: "documents/cv/Alessandro_Esposito_CV_ITA.pdf" },
  },
  snapshot: [
    {
      label: "Focus",
      value: "IT strategy, advisory, project management, infrastructure governance",
    },
    {
      label: "Output",
      value: "Roadmap IT, trasformazione digitale, continuita operativa, disaster recovery",
    },
    {
      label: "Approccio",
      value: "Business outcome, stakeholder management, delivery tecnica misurabile",
    },
  ],
  profile: {
    eyebrow: "Profilo",
    title: "Strategia IT e delivery tecnica per trasformare esigenze di business in soluzioni misurabili.",
    paragraphs: [
      "Sono un IT Consultant con esperienza nella gestione di progetti IT complessi, dalla fase di pre-sales alla delivery tecnica e al supporto post-produzione.",
      "Ho lavorato in una giovane azienda italiana coordinando team cross-funzionali, contribuendo alla progettazione di architetture scalabili e introducendo pratiche DevOps, integrazione tra sistemi legacy e piattaforme cloud.",
      "Mantengo un forte orientamento al business: facilito il dialogo con gli stakeholder e traduco esigenze operative in soluzioni tecnologiche concrete, sostenibili e misurabili.",
    ],
  },
  capabilities: {
    eyebrow: "Competenze e Case Study",
    title: "Competenze applicate in progetti reali",
    items: [
      {
        id: "it-strategy-roadmap",
        number: "01",
        title: "IT Strategy & Roadmap",
        copy: "Definizione di strategie IT e roadmap evolutive allineate a obiettivi di business, efficienza e sostenibilita.",
        caseStudyId: "lamborghini-it-strategy",
      },
      {
        id: "business-continuity-disaster-recovery",
        number: "02",
        title: "Business Continuity & Disaster Recovery",
        copy: "Piani, infrastrutture e misure operative per protezione dei dati, resilienza e continuita dei servizi.",
        caseStudyId: "we-build-os-obsolescence",
      },
      {
        id: "digital-transformation",
        number: "03",
        title: "Digital Transformation",
        copy: "Modernizzazione di processi aziendali, soluzioni IT ad hoc, infrastrutture cloud private e integrazione ERP.",
        caseStudyId: "we-build-hfm-db-replacement",
      },
      {
        id: "project-vendor-management",
        number: "04",
        title: "Project & Vendor Management",
        copy: "Coordinamento stakeholder, fornitori IT, team di delivery, tempi, budget, obiettivi e performance contrattuali.",
        caseStudyId: "lamborghini-dlm-selection",
      },
    ],
  },
  caseStudies: {
    eyebrow: "Case study",
    title: "Case study collegati alle competenze",
    items: [
      {
        id: "lamborghini-it-strategy",
        tag: "IT Strategy",
        client: "Automobili Lamborghini S.p.A.",
        company: "Vargroup S.p.A.",
        title: "Roadmap IT e governance multi-cloud",
        copy: "Definizione di strategie e roadmap evolutive su un contesto enterprise con due data center in business continuity, VMware vSphere, NetApp MetroCluster, Cisco Nexus, oltre 1000 VM tra produzione, office, VDI e DMZ, rete segmentata tramite VRF e sicurezza gestita con firewall Cisco ASA e Palo Alto.",
        evidence: "La competenza usata qui riguarda la traduzione degli obiettivi di business in una roadmap eseguibile: maggiore continuita operativa, architettura piu flessibile e sostenibile, percorso concreto di modernizzazione e adozione di servizi cloud avanzati.",
        capabilities: ["IT Strategy & Roadmap", "Infrastructure Governance", "Business Continuity", "Modernization"],
      },
      {
        id: "we-build-os-obsolescence",
        tag: "Infrastructure Governance",
        client: "Webuild",
        company: "Case study da dettagliare",
        title: "Gestione obsolescenza OS su parco VM",
        copy: "Assessment, prioritizzazione e governance della sostituzione o aggiornamento dei sistemi operativi obsoleti su macchine virtuali, con attenzione a compatibilita applicativa, continuita operativa e riduzione del rischio.",
        evidence: "La competenza usata qui riguarda controllo del rischio infrastrutturale, pianificazione degli interventi, dipendenze applicative e coordinamento operativo.",
        capabilities: ["Business Continuity & Disaster Recovery", "Infrastructure Governance", "Project Management"],
      },
      {
        id: "we-build-hfm-db-replacement",
        tag: "Database Modernization",
        client: "Webuild",
        company: "Case study da dettagliare",
        title: "Sostituzione DB di Hyperion Financial Management",
        copy: "Gestione del percorso di sostituzione database a supporto di Hyperion Financial Management, con presidio di compatibilita, finestre operative, rollback plan e continuita dei processi finance.",
        evidence: "La competenza usata qui riguarda modernizzazione tecnica di componenti critici, gestione stakeholder finance/IT e riduzione del rischio durante il cambiamento.",
        capabilities: ["Digital Transformation", "Database Migration", "Business Continuity"],
      },
      {
        id: "onduline-idrotirrena-project-management",
        tag: "Project Management",
        client: "Onduline S.p.A. / IDROTIRRENA S.C.A.R.L.",
        company: "Alpha Team S.R.L.",
        title: "Business Continuity, Disaster Recovery e modernizzazione IT",
        copy: "Pianificazione e coordinamento di iniziative IT per continuita operativa, disaster recovery e digital transformation, con analisi requisiti, documentazione ITSM, audit infrastrutturali e soluzioni su misura.",
        evidence: "La competenza usata qui riguarda la gestione end-to-end del progetto: pre-sales, analisi, coordinamento fornitori, delivery e supporto operativo.",
        capabilities: ["Project & Vendor Management", "Business Continuity", "ITSM"],
      },
      {
        id: "lamborghini-dlm-selection",
        tag: "Software Selection",
        client: "Automobili Lamborghini S.p.A.",
        company: "Vargroup S.p.A.",
        title: "SW Selection DLM",
        copy: "Percorso di kick-off e selezione software per iniziative DLM, con impostazione del confronto tra esigenze, stakeholder, opzioni tecnologiche e criteri decisionali.",
        evidence: "La competenza usata qui riguarda strutturazione della domanda, governance del processo decisionale, raccolta requisiti e allineamento tra business, IT e vendor.",
        capabilities: ["Project & Vendor Management", "Software Selection", "Stakeholder Management"],
      },
      {
        id: "teamsystem-erp-infrastructure",
        tag: "ERP & Infrastructure",
        client: "Costanter S.p.A.",
        company: "Alpha Team S.R.L.",
        title: "Gestione infrastrutturale ERP TeamSystem",
        copy: "Configurazione e gestione del ciclo di vita di ambienti infrastrutturali ERP TeamSystem, garantendo prestazioni, scalabilita e allineamento ai requisiti operativi.",
        evidence: "La competenza usata qui riguarda gestione infrastrutturale, operations, affidabilita e mantenimento di piattaforme business critical.",
        capabilities: ["System Engineering", "ERP", "Operations"],
      },
    ],
  },
  journey: {
    eyebrow: "Percorso",
    title: "Percorso professionale organizzato su una linea temporale aggiornabile.",
    items: [
      {
        years: "2025 - Oggi",
        role: "IT Strategy & Advisor Consultant",
        company: "Vargroup S.p.A.",
        copy: "Consulenza strategica e advisory IT su roadmap evolutive, governance tecnologica, coordinamento stakeholder e supporto a programmi complessi di trasformazione digitale.",
        tags: ["IT Strategy", "Roadmap", "Multi-cloud", "Disaster Recovery"],
      },
      {
        years: "2024 - 2025",
        role: "IT Project Manager",
        company: "Alpha Team S.R.L.",
        copy: "Pianificazione, gestione e coordinamento di progetti IT per continuita operativa, disaster recovery, trasformazione digitale e modernizzazione dei processi.",
        tags: ["Project Management", "BC/DR", "ITSM", "Digital Transformation"],
      },
      {
        years: "2022 - 2024",
        role: "System Engineer",
        company: "Alpha Team S.R.L.",
        copy: "Gestione, configurazione e presidio operativo di ambienti infrastrutturali, con attenzione a prestazioni, scalabilita e requisiti di business.",
        tags: ["System Engineering", "ERP", "Infrastructure", "Operations"],
      },
      {
        years: "2021 - 2022",
        role: "Esperienza professionale in ambito IT",
        company: "GUIBIZ",
        copy: "Esperienza iniziale in contesto IT, utile a consolidare basi operative, orientamento al cliente e comprensione dei processi tecnici di supporto.",
        tags: ["IT", "Operations", "Customer orientation"],
      },
      {
        years: "2025 - Oggi",
        role: "Percorso universitario in ambito informatico",
        company: "Universita Telematica Pegaso",
        copy: "Formazione accademica orientata alle discipline informatiche, utile a consolidare basi tecniche, metodo e capacita di lettura dei sistemi digitali complessi.",
        tags: ["Formazione", "Informatica", "Universita"],
      },
    ],
  },
  certificates: {
    eyebrow: "Certificati",
    title: "Certificazioni e attestati professionali.",
    intro:
      "Sezione alimentata dai PDF presenti in documents/certificates. Aggiungi nuovi file nella cartella e una voce in questo elenco.",
    items: [
      {
        title: "Qualificazione ISIPM-Base",
        issuer: "ISIPM",
        year: "2025",
        file: "documents/certificates/Attestato Qualificazione ISIPM-Base.pdf",
      },
      {
        title: "TS Enterprise Tecnico",
        issuer: "TeamSystem",
        year: "2025",
        file: "documents/certificates/Certificazione TS Enterprise Tecnico - Esposito_Alessandro.pdf",
      },
      {
        title: "OKR Coach Academy",
        issuer: "OKR Coach Academy",
        year: "2025",
        file: "documents/certificates/Attestato_OKR Coach Academy_Esposito.pdf",
      },
      {
        title: "Direttiva NIS2",
        issuer: "Network and Information Security",
        year: "2025",
        file: "documents/certificates/Attestato_Direttiva NIS2 (Network and Information Security)_Esposito.pdf",
      },
      {
        title: "Data Literacy",
        issuer: "Webinar Data Literacy",
        year: "2026",
        file: "documents/certificates/Attestato_Webinar Data Literacy - 01_04_2026_Esposito.pdf",
      },
      {
        title: "DPA e NDA",
        issuer: "Data Processing Agreement e Non Disclosure Agreement",
        year: "2025",
        file: "documents/certificates/Attestato_DPA and NDA Istruzioni per l'uso_Esposito.pdf",
      },
      {
        title: "Subappalto e Sub-Responsabile del trattamento",
        issuer: "Formazione compliance",
        year: "2025",
        file: "documents/certificates/Attestato Subappalto e Sub-Responsabile del trattamento Esposito.pdf",
      },
      {
        title: "Diversity, Equity & Inclusion",
        issuer: "LDP OPEN",
        year: "2025",
        file: "documents/certificates/Attestato_LDP OPEN - Diversity Equity Inclusion_Esposito.pdf",
      },
      {
        title: "Sustainability",
        issuer: "Var Group",
        year: "2025",
        file: "documents/certificates/Attestato_Sustainability Var Group_Esposito.pdf",
      },
    ],
  },
  contact: {
    eyebrow: "Contatti",
    title: "Per opportunita, collaborazioni o confronti tecnici.",
    actions: [
      { label: "Email", target: "mailto:espositoalessandro1997@gmail.com", variant: "primary" },
      {
        label: "LinkedIn",
        target: "https://www.linkedin.com/in/alessandro-esposito-0880751a6/",
        variant: "secondary",
        external: true,
      },
      { label: "Apri CV", target: "documents/cv/Alessandro_Esposito_CV_ITA.pdf", variant: "secondary" },
    ],
  },
  footer: {
    copyright: "© 2026 Alessandro Esposito",
    backToTop: "Torna su",
  },
};
